# Generated by Django 5.2.8 on 2026-01-03 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.TextField(choices=[('Condo', 'Condo'), ('Villa', 'Villa'), ('Apartment', 'Apartment'), ('Penthouse', 'Penthouse'), ('Mansion', 'Mansion'), ('Warehouse', 'Warehouse'), ('Retail Store', 'Retail Store'), ('Office Space', 'Office Space')], default='Apartment', max_length=20)),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('title', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('status', models.TextField(choices=[('Draft', 'Draft'), ('Pending GM Approval', 'Pending GM Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Archived', 'Archived')], default='Draft', max_length=30)),
                ('gm_approved_at', models.DateTimeField(blank=True, null=True)),
                ('gm_rejection_rsn', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='org.branch')),
                ('gm_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
