# Generated by Django 5.2.8 on 2026-01-12 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='assigned_salesman',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Salesman'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_salesmen', to=settings.AUTH_USER_MODEL),
        ),
    ]
