# Generated by Django 5.2.8 on 2026-01-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_listing_assigned_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='commentss',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
