# Generated by Django 5.2.8 on 2026-01-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_listing_commentss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='commentss',
            new_name='comments',
        ),
    ]
