# Generated by Django 5.2.8 on 2026-01-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_commentss_listing_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
