# Generated by Django 5.2.8 on 2026-01-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_listing_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.TextField(choices=[('Draft', 'Draft'), ('Pending Initial Approval', 'Pending Initial Approval'), ('Rejected', 'Rejected'), ('Prospecting', 'Prospecting'), ('Negotiating', 'Negotiating'), ('Pending Final Approval', 'Pending Final Approval'), ('Closed', 'Closed')], default='Draft', max_length=30),
        ),
    ]
