# Generated by Django 5.2.8 on 2026-01-27 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_listing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='gm_approved_at',
            new_name='lead_approved_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='gm_approved_by',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='gm_rejection_rsn',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
        migrations.AddField(
            model_name='listing',
            name='lead_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='lead_status',
            field=models.TextField(choices=[('Approval Pending', 'Approval Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Approval Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='opp_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='opp_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='opp_status',
            field=models.TextField(choices=[('Proespecting', 'Prospecting'), ('Negotiating', 'Negotiating'), ('Pending Approval', 'Pending Approval'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending Approval', max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='sale_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='sale_status',
            field=models.TextField(choices=[('Processing', 'Processing'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed List')], default='Processing', max_length=30),
        ),
    ]
