# Generated by Django 5.2.8 on 2026-01-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_gm_approved_at_listing_lead_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
