# Generated by Django 6.0.1 on 2026-02-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_listing_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='opp_status',
            field=models.TextField(blank=True, choices=[('Proespecting', 'Prospecting'), ('Negotiating', 'Negotiating'), ('Pending Approval', 'Pending Approval'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending Approval', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_status',
            field=models.TextField(blank=True, choices=[('Processing', 'Processing'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed List')], default='Processing', max_length=30, null=True),
        ),
    ]
