# Generated by Django 6.0.1 on 2026-02-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_listing_comments_alter_listing_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='opp_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
