# Generated by Django 6.0.1 on 2026-02-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_listing_opp_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='opp_status',
            field=models.TextField(blank=True, choices=[('Prospecting', 'Prospecting'), ('Negotiating', 'Negotiating'), ('Pending', 'Pending Approval'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_status',
            field=models.TextField(blank=True, choices=[('Processing', 'Processing'), ('ClosedW', 'Closed Won'), ('ClosedL', 'Closed Lost')], null=True),
        ),
    ]
