# Generated by Django 6.0.1 on 2026-02-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_listing_opp_status_alter_listing_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.TextField(choices=[('Villa', 'Villa'), ('Apartment', 'Apartment'), ('Warehouse', 'Warehouse'), ('Retail', 'Retail Store'), ('Office', 'Office Space')], default='Villa'),
        ),
    ]
